language: generic

sudo: required
services:
  - docker

before_install:
  - docker build -t kkteng/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true kkteng/react-test npm test


after_success:
  - docker build -t kkteng/multi-client ./client
  - docker build -t kkteng/multi-nginx ./nginx
  - docker build -t kkteng/multi-server ./server
  - docker build -t kkteng/multi-worker ./worker
  - echo "$DOCKER_PW" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push kkteng/multi-client
  - docker push kkteng/multi-nginx
  - docker push kkteng/multi-server
  - docker push kkteng/multi-worker

deploy:
  edge: true
  provider: elasticbeanstalk
  region: "ap-southeast-1"
  app: "multi-docker"
  env: "MultiDocker-env"
  bucket_name: "elasticbeanstalk-ap-southeast-1-618300318837"
  bucket_path: "docker-multi"
  on:
    branch: master 
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY

